import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    mainContainer: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: Spacing["5xl"],
    },
    container: {
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.xl,
    },
    // Header
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing["2xl"],
      paddingBottom: Spacing.md,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    logoutButton: {
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.lg,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#FFE8EE',
    },
    logoutText: {
      fontSize: 14,
      fontWeight: '700',
      color: '#EF4444',
    },
    // Tab 切换
    tabWrapper: {
      backgroundColor: 'transparent',
      paddingHorizontal: Spacing.lg,
    },
    tabContainerContent: {
      paddingRight: Spacing.lg,
    },
    tabScroll: {
      flexDirection: 'row',
      backgroundColor: '#EDE8FF',
      borderRadius: BorderRadius.xl,
      padding: Spacing.xs,
    },
    manageTabFixed: {
      flexDirection: 'row',
      backgroundColor: '#EDE8FF',
      borderRadius: BorderRadius.xl,
      padding: Spacing.xs,
      marginHorizontal: Spacing.lg,
      marginTop: Spacing.sm,
      marginBottom: Spacing.sm,
    },
    manageTabWrapper: {
      marginBottom: Spacing.lg,
    },
    tab: {
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      alignItems: 'center',
      borderRadius: BorderRadius.lg,
      marginRight: Spacing.xs,
    },
    tabActive: {
      backgroundColor: '#FFFFFF',
      shadowColor: '#7C5CFC',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    tabText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    tabTextActive: {
      color: theme.primary,
    },
    // 卡片
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius["2xl"],
      padding: Spacing.lg,
      marginBottom: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: '#7C5CFC',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 6,
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.textPrimary,
      flex: 1,
    },
    cardBadge: {
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.md,
    },
    badgePending: {
      backgroundColor: '#FFF4DD',
    },
    badgeApproved: {
      backgroundColor: '#E0F8EC',
    },
    badgeRejected: {
      backgroundColor: '#FFE8EE',
    },
    badgeText: {
      fontSize: 12,
      fontWeight: '700',
    },
    cardInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: Spacing.sm,
    },
    cardPoints: {
      fontSize: 14,
      fontWeight: '700',
      color: '#FFCB57',
      marginLeft: Spacing.xs,
    },
    cardDate: {
      fontSize: 12,
      fontWeight: '500',
      color: theme.textSecondary,
      marginLeft: 'auto',
    },
    cardSubtitle: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textSecondary,
      marginTop: Spacing.xs,
    },
    // 按钮
    buttonRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.md,
    },
    approveButton: {
      flex: 1,
      backgroundColor: '#5ED6A0',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.sm,
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    approveButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    rejectButton: {
      flex: 1,
      backgroundColor: '#FF8FAB',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.sm,
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    rejectButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    editButton: {
      flex: 1,
      backgroundColor: '#7C5CFC',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.sm,
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    editButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    deleteButton: {
      flex: 1,
      backgroundColor: '#FF8FAB',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.sm,
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    deleteButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    primaryButton: {
      backgroundColor: theme.primary,
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing["2xl"],
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
      shadowColor: '#5A3ED9',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
      marginTop: Spacing.md,
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    addButton: {
      backgroundColor: '#5ED6A0',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.xl,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: Spacing.lg,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    addButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
      marginLeft: Spacing.sm,
    },
    // 统计
    statsRow: {
      flexDirection: 'row',
      marginBottom: Spacing.lg,
      gap: Spacing.md,
    },
    statCard: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius["2xl"],
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.md,
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: '#7C5CFC',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 6,
    },
    statValue: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    statLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textSecondary,
      marginTop: Spacing.xs,
    },
    // 空状态
    emptyContainer: {
      alignItems: 'center',
      paddingVertical: Spacing["4xl"],
    },
    emptyText: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.textSecondary,
      marginTop: Spacing.lg,
    },
    // Modal
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius["2xl"],
      padding: Spacing.xl,
      width: '90%',
      maxWidth: 400,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.textPrimary,
      marginBottom: Spacing.lg,
      textAlign: 'center',
    },
    modalInput: {
      backgroundColor: '#F5F3FF',
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.lg,
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
      marginBottom: Spacing.md,
      borderWidth: 1,
      borderColor: '#E5E1FF',
    },
    modalPicker: {
      backgroundColor: '#F5F3FF',
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.md,
      borderWidth: 1,
      borderColor: '#E5E1FF',
    },
    modalButtonRow: {
      flexDirection: 'row',
      gap: Spacing.md,
      marginTop: Spacing.lg,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: '#F3F4F6',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.md,
      alignItems: 'center',
    },
    cancelButtonText: {
      color: theme.textSecondary,
      fontSize: 15,
      fontWeight: '700',
    },
    saveButton: {
      flex: 1,
      backgroundColor: '#7C5CFC',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.md,
      alignItems: 'center',
    },
    saveButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '700',
    },
    // 分类标签
    categoryBadge: {
      borderRadius: BorderRadius.md,
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.sm,
    },
    categoryHousework: {
      backgroundColor: '#FFF4DD',
    },
    categoryStudy: {
      backgroundColor: '#E0F8EC',
    },
    categorySelfDiscipline: {
      backgroundColor: '#EDE8FF',
    },
    // 选择器
    pickerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#F5F3FF',
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.lg,
      marginBottom: Spacing.md,
      borderWidth: 1,
      borderColor: '#E5E1FF',
    },
    pickerButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    // 孩子选择
    childSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius.xl,
      padding: Spacing.md,
      marginBottom: Spacing.lg,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    childAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#EDE8FF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    childName: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.textPrimary,
      marginLeft: Spacing.md,
    },
    childPoints: {
      fontSize: 14,
      fontWeight: '700',
      color: '#FFCB57',
      marginLeft: 'auto',
    },
    // 记录列表
    recordItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: '#F3F4F6',
    },
    recordPoints: {
      fontSize: 16,
      fontWeight: '800',
      marginLeft: Spacing.sm,
      flexShrink: 0,  // 防止被压缩
    },
    recordPointsPositive: {
      color: '#10B981',
    },
    recordPointsNegative: {
      color: '#EF4444',
    },
    recordDesc: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
      flex: 1,
    },
    recordDate: {
      fontSize: 12,
      fontWeight: '500',
      color: theme.textSecondary,
    },
    // 新增样式
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.textPrimary,
      marginBottom: Spacing.md,
    },
    recordTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    modalBody: {
      maxHeight: 400,
    },
    formLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
      marginBottom: Spacing.sm,
      marginTop: Spacing.md,
    },
    formLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.sm,
      marginTop: Spacing.md,
    },
    helpIcon: {
      marginLeft: Spacing.sm,
      padding: Spacing.xs,
    },
    formInput: {
      backgroundColor: '#F5F3FF',
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.lg,
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
      borderWidth: 1,
      borderColor: '#E5E1FF',
    },
    pickerRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    pickerOption: {
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#F5F3FF',
      borderWidth: 1,
      borderColor: '#E5E1FF',
    },
    pickerOptionActive: {
      backgroundColor: '#7C5CFC',
      borderColor: '#7C5CFC',
    },
    pickerOptionText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    pickerOptionTextActive: {
      color: '#FFFFFF',
      fontWeight: '700',
    },
    modalFooter: {
      flexDirection: 'row',
      gap: Spacing.md,
      marginTop: Spacing.xl,
    },
    // 查看更多按钮
    loadMoreButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.lg,
      marginTop: Spacing.sm,
    },
    loadMoreText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
      marginRight: Spacing.xs,
    },
    // 存款按钮
    depositButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#3B82F6',
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.md,
      gap: Spacing.xs,
    },
    depositButtonText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '700',
    },
    // 重置按钮
    resetButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#EF4444',
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing["2xl"],
      marginTop: Spacing["2xl"],
      marginBottom: Spacing.xl,
      gap: Spacing.sm,
    },
    resetButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    // 数据统计Tab
    statsTabContainer: {
      flexDirection: 'row',
      backgroundColor: '#EDE8FF',
      borderRadius: BorderRadius.xl,
      padding: Spacing.xs,
      marginTop: Spacing.lg,
      marginBottom: Spacing.md,
    },
    statsTab: {
      flex: 1,
      paddingVertical: Spacing.sm,
      alignItems: 'center',
      borderRadius: BorderRadius.lg,
    },
    statsTabActive: {
      backgroundColor: '#FFFFFF',
      shadowColor: '#7C5CFC',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    statsTabText: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    statsTabTextActive: {
      color: theme.primary,
    },
    // 表单提示文字
    formHint: {
      fontSize: 12,
      fontWeight: '500',
      color: theme.textSecondary,
      marginTop: Spacing.xs,
      marginBottom: Spacing.md,
      lineHeight: 18,
    },
  });
};
